version: '3.3'

services:
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=r00tpass
    ports:
      - "3406:3306"
    restart: always

  messenger:
    image: dedeli1989/messenger-service:latest
    container_name: messenger-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    restart: always

    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/messenger?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: r00tpass
      SPRING_PROFILES_ACTIVE: docker
